baseURL = "http://example.org/"
languageCode = "ru-RU"
title = "Гарри и вагон косяков"

[params]
custom_css = ["css/custom.css"]
custom_js = ["js/custom.js"]

[markup.goldmark.renderer]
unsafe = true
